### PR TITLE
drm/panel: Revert Tianma panel name to tl052vdxp02

### PR DESCRIPTION
**Pull request by nathanjensen1**
When the panel drivers were generated for msm8953-6.0.10, the Tianma panel for the Moto G5 Plus was changed from tl052vdxp02 to tl052vdpx02. I have found a data sheet for the panel confirming that the original spelling was correct

### CODE REVIEW

**Comment by z3ntu** [comment]
Please change it here https://github.com/msm8953-mainline/linux-panel-drivers/blob/master/config/motorola-potter.sh#L6 and then we can regenerate the panel driver with that. Otherwise it'll be wrong again next time this is done.

**Comment by nathanjensen1** [comment]
Okay. The new pull request is here https://github.com/msm8953-mainline/linux-panel-drivers/pull/1

**Comment by z3ntu** [comment]
Should be fixed with 1a5dbe9612cc, please double check :)

**Comment by nathanjensen1** [comment]
Looks good to me

**Pull request closed without merging**
