### PR TITLE
6.5.2/ipa

### PR DESCRIPTION
**Pull request by alikates**
Add IPA driver but with data transactions disabled to prevent crashing the phone. This way we can have calls and SMS with ModemManager.

### CODE REVIEW

**Comment by spasswolf** [comment]
Are there any details known about the crash when using mobile data? I tried to capture a debug message using netconsole over usb ethernet (cdc_ether) but got nothing ...

**Comment by spasswolf** [comment]
To test the mobile data crash issue I cherry-picked the old ipa patches on top of 6.6.10. There the crash does not occur but when I try to ping something I get errors like these:
```
[ 2180.419735] ipa 7940000.ipa: unexpected tagged packet from endpoint 4
[ 2181.456583] ipa 7940000.ipa: unexpected tagged packet from endpoint 4
[...]
```
The code is in branch v6.6.10_ipa_old of https://github.com/spasswolf/msm8953-linux.git

**Comment by spasswolf** [comment]
The crash when using mobile  data with the new ipa_legacy driver occurs when using bam dma with the ap_modem_tx dma channel (the ap_modem_rx and ap_lan_rx channels do not crash).

**Comment by barni2000** [comment]
Did you reverted this commit https://github.com/msm8953-mainline/linux/pull/132/commits/e7797492485f14684f5575f82800d09508df2034. It was an effort for disable data.

**Comment by spasswolf** [comment]
Yes, I try to investigate the cause of the problem as it does not occur in the old IPA driver (i.e. the combined v2 and v3 driver).

**Comment by spasswolf** [comment]
I cannot find the error in the new-legacy driver so I'm trying to recreate it from the old IPA v2+v3 driver by removing the v3+ stuff while checking trying to preserve the mobile data behaviour.
Code can be found in https://github.com/spasswolf/msm8953-linux.git branch v6.6.10_new_legacy.

**Comment by spasswolf** [comment]
Found an error in ipa_legacy, unfortunately is still crashes:
```
diff --git a/drivers/net/ipa-legacy/ipa_cmd.c b/drivers/net/ipa-legacy/ipa_cmd.c
index f880cc317838..56e98c4074a1 100644
--- a/drivers/net/ipa-legacy/ipa_cmd.c
+++ b/drivers/net/ipa-legacy/ipa_cmd.c
@@ -45,8 +45,8 @@ enum pipeline_clear_options {
 /* IPA_CMD_IP_V{4,6}_{FILTER,ROUTING}_INIT */
 
 struct ipa_cmd_hw_ip_fltrt_init {
-       __le64 hash_rules_addr;
-       __le64 flags;
+       __le32 hash_rules_addr;
+       __le32 flags;
 };
 
 /* Field masks for ipa_cmd_hw_ip_fltrt_init structure fields */
@@ -59,7 +59,7 @@ struct ipa_cmd_hw_ip_fltrt_init {
 /* IPA_CMD_HDR_INIT_LOCAL */
 
 struct ipa_cmd_hw_hdr_init_local {
-       __le64 hdr_table_addr;
+       __le32 hdr_table_addr;
        __le32 flags;
 };
 

```

**Comment by barni2000** [comment]
Check 6.7.0/main, there is an new driver there and mobile data works with it.

**Comment by spasswolf** [comment]
Tested 6.7.0/main with debian stable userspace, SMS works and mobile data doesn't crash, but I get the a similar problem as with the old driver, when I ping I don't get return packets.

I get a network interface when enabling mobile data:
```
$ ip addr show qmapmux0.0
8: qmapmux0.0@rmnet_ipa0: <UP,LOWER_UP> mtu 1496 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[519] 
    inet 10.209.254.139/29 brd 10.209.254.143 scope global noprefixroute qmapmux0.0
       valid_lft forever preferred_lft forever

```
and the following routes (output from ip route):
```
default via 10.209.254.140 dev qmapmux0.0 proto static metric 1050 
10.209.254.136/29 dev qmapmux0.0 proto kernel scope link src 10.209.254.139 metric 1050 
```
When I ping 10.209.254.140 I get after 10 packets:
```
$ cat /proc/net/dev | grep -E "rmnet|qmap|Inter|face"
Inter-|   Receive                                                |  Transmit
 face |             bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
rmnet_ipa0:      40      10    0    0    0     0          0         0      880      10    0   12    0     0       0          0
qmapmux0.0:       0       0    0    0    0     0          0         0      880      10    0    0    0     0       0          0

```
This is a slight improvement over the old driver, as I at least get rx packets in rmnet_ipa0 (with the old driver all receive numbers were 0). 
Does this work in postmarketOS? Might this be a userspace issue? (I enabled mobile data by clicking the gnome thing ...)

**Comment by barni2000** [comment]
> Tested 6.7.0/main with debian stable userspace, SMS works and mobile data doesn't crash, but I get the a similar problem as with the old driver, when I ping I don't get return packets.
> 
> I get a network interface when enabling mobile data:
> 
> ```
> $ ip addr show qmapmux0.0
> 8: qmapmux0.0@rmnet_ipa0: <UP,LOWER_UP> mtu 1496 qdisc pfifo_fast state UNKNOWN group default qlen 1000
>     link/[519] 
>     inet 10.209.254.139/29 brd 10.209.254.143 scope global noprefixroute qmapmux0.0
>        valid_lft forever preferred_lft forever
> ```
> 
> and the following routes (output from ip route):
> 
> ```
> default via 10.209.254.140 dev qmapmux0.0 proto static metric 1050 
> 10.209.254.136/29 dev qmapmux0.0 proto kernel scope link src 10.209.254.139 metric 1050 
> ```
> 
> When I ping 10.209.254.140 I get after 10 packets:
> 
> ```
> $ cat /proc/net/dev | grep -E "rmnet|qmap|Inter|face"
> Inter-|   Receive                                                |  Transmit
>  face |       bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
> rmnet_ipa0:      40      10    0    0    0     0          0         0      880      10    0   12    0     0       0          0
> qmapmux0.0:       0       0    0    0    0     0          0         0      880      10    0    0    0     0       0          0
> ```
> 
> This is a slight improvement over the old driver, as I at least get rx packets in rmnet_ipa0 (with the old driver all receive numbers were 0). Does this work in postmarketOS? Might this be a userspace issue? (I enabled mobile data by clicking the gnome thing ...)

ping works for me on xiaomi-vince

**Comment by spasswolf** [comment]
With postmarketOS as userspace?

**Comment by barni2000** [comment]
> With postmarketOS as userspace? yes

**Comment by spasswolf** [comment]
Mobile data works now for me with 6.7.0/main and ipa2-lite and debian stable (bookworm) as userspace. Trying to ping was actually a bad idea, that's still not working, but I can ping e.g. 1.1.1.1 and also access wikipedia with firefox-esr.

**Comment by barni2000** [comment]
I think this MR should be close.

**Pull request closed without merging**
