### PR TITLE
Add support for Xiaomi Mi A1 (tissot)

### PR DESCRIPTION
**Pull request by JIaxyga**

### CODE REVIEW

**Comment by SirSireesh** [comment]
Could you please change the indentation to tabs? Other than that LGTM

**Comment by JIaxyga** [comment]
> Could you please change the indentation to tabs? Other than that LGTM

Only tabulation is used everywhere. Maybe I missed something?

**Comment by SirSireesh** [comment]
See the "Files changed" tab, in the diff all the indentations in the panel driver files are 2 spaces

**Comment by minlexx** [comment]
> in the panel driver files are 2 spaces

This seems like weird github display bug, if you click "View file" it looks OK? 

https://github.com/msm8953-mainline/linux/blob/920fdee2595a1f1a6e8932c681eecf086a2a74bb/drivers/gpu/drm/panel/panel-ft8716-fhd.c

**Comment by SirSireesh** [comment]
@minlexx you're right, thanks! Weird bug...

**Pull request merged**
