### PR TITLE
arm64: dts: qcom: msm8953-xiaomi-vince: add BMI120 alternative accele…

### PR DESCRIPTION
**Pull request by M0Rf30**
…rometer

This commit enable Bosch BMI120 accelerometer found on some xiaomi-vince variants.

### CODE REVIEW

**Comment by M0Rf30** [comment]
@fekz115 @alikates @z3ntu

Config fragment also updated here (BMI160)
https://github.com/msm8953-mainline/linux/pull/91

**Comment by fekz115** [comment]
Confirm that it is works

**Comment by JIaxyga** [comment]
I think it is necessary to leave the light-sensor, because it is indicated in the documentation. I mistakenly wrote light for tissot

**Comment by JIaxyga** [comment]
It would also be nice to check the documentation of the other sensors

**Comment by JIaxyga** [comment]
I also suggest giving labels for sensors like in tissot. Then it will be clearer in the userspace which sensor gives feedback

**Comment by JIaxyga** [comment]
> I also suggest giving labels for sensors like in tissot. Then it will be clearer in the userspace which sensor gives feedback
I'm not sure if this is how it works and need to check

**Comment by M0Rf30** [comment]
> > I also suggest giving labels for sensors like in tissot. Then it will be clearer in the userspace which sensor gives feedback
> 
> I'm not sure if this is how it works and need to check

looking at the codebase there are not so many labels for sensors, a lot of them are for buttons and temp

**Comment by alikates** [comment]
Is this ready for merging then?

**Comment by M0Rf30** [comment]
Yes

**Pull request merged**
