### PR TITLE
Add ipa patches and alternate msm8953 configuarion for qcom_q6v5_mss, along with support for ocean

### PR DESCRIPTION
**Pull request by Ultracoolguy**

### CODE REVIEW

**Comment by Ultracoolguy** [comment]
Ok it looks like there are some commits there that I can just remove(mainly arch/arm64/configs related)

**Comment by Ultracoolguy** [comment]
There we go.

**Comment by z3ntu** [comment]
You should probably add a Signed-off-by line to your commits?

**Comment by Ultracoolguy** [comment]
@z3ntu Done.

**Comment by SirSireesh** [comment]
Oh I guess I missed signed-off-by on my commits dma related commits... I'll add them when I rebase locally

**Pull request merged**
