### PR TITLE
Re enable motorola-ali

### PR DESCRIPTION
**Pull request by M0Rf30**
@julianbraha
in latest 6.0.10 seems that motorola-ali is missing.
Let's try to fix it :smile: 

Maybe panel should be added by the panel-generator?

### CODE REVIEW

**Comment by z3ntu** [comment]
Please before reintroducing make sure all commits have proper sign-off

**Comment by M0Rf30** [comment]
> Please before reintroducing make sure all commits have proper sign-off, every single commit going into this repo should have a sign-off from the author before merging

Done

**Comment by z3ntu** [comment]
@julianbraha Please confirm Signed-off-by for these patches https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Comment by alikates** [comment]
Hi, i I cherry picked your commits so no need to rebase. I had to fix a small indentation issue in the root node, please next time make sure its all tabs. 

I guess we can close this as soon as you confirm everything works fine.

**Comment by M0Rf30** [comment]
I updated the MR:
https://gitlab.com/postmarketOS/pmaports/-/merge_requests/3697
following this branch

**Pull request closed without merging**
