### PR TITLE
Add BLSP DMAs for I2C

### PR DESCRIPTION
**Pull request by z3ntu**
Upstream links:
* https://lore.kernel.org/linux-arm-msm/20230422-msm8953-blsp-dma-v1-1-0024801bb587@z3ntu.xyz/T/

### CODE REVIEW

**Comment by alikates** [comment]
I'm testing it in daisy and I'm getting a lot of messages like this in dmesg

```
[    2.171636] i2c_qup 78b6000.i2c: using default clock-frequency 100000
[    2.171755] i2c_qup 78b6000.i2c: 
                tx channel not available
[    2.177438] i2c_qup 78b7000.i2c: using default clock-frequency 100000
[    2.183885] i2c_qup 78b7000.i2c: 
                tx channel not available
[    2.191397] i2c_qup 78b6000.i2c: using default clock-frequency 100000
```
Do you know why is that? Maybe TZ not allowing using the i2c controller?

**Comment by z3ntu** [comment]
Interesting, any message from the dma driver?

"tx channel not available" message is printed when it cannot get the dma (which normally is not fatal since the i2c driver can also work without dma)

**Comment by z3ntu** [comment]
I've split out the GPIO part to #97

@alikates Can you please post full dmesg, and `zcat /proc/config.gz` please?

**Comment by alikates** [comment]
I tested it again but now I found it it's working. Actually the errors I reported before are EPROBE_DEFER, so it ends up picking up the DMA channels.

Also:
```
/home/user # cat /sys/class/dma/dma1chan*/slave/uevent 
DRIVER=i2c_qup
OF_NAME=i2c
OF_FULLNAME=/soc@0/i2c@78b6000
OF_COMPATIBLE_0=qcom,i2c-qup-v2.2.1
OF_COMPATIBLE_N=1
MODALIAS=of:Ni2cT(null)Cqcom,i2c-qup-v2.2.1
DRIVER=i2c_qup
OF_NAME=i2c
OF_FULLNAME=/soc@0/i2c@78b6000
OF_COMPATIBLE_0=qcom,i2c-qup-v2.2.1
OF_COMPATIBLE_N=1
MODALIAS=of:Ni2cT(null)Cqcom,i2c-qup-v2.2.1
DRIVER=i2c_qup
OF_NAME=i2c
OF_FULLNAME=/soc@0/i2c@78b7000
OF_COMPATIBLE_0=qcom,i2c-qup-v2.2.1
OF_COMPATIBLE_N=1
MODALIAS=of:Ni2cT(null)Cqcom,i2c-qup-v2.2.1
DRIVER=i2c_qup
OF_NAME=i2c
OF_FULLNAME=/soc@0/i2c@78b7000
OF_COMPATIBLE_0=qcom,i2c-qup-v2.2.1
OF_COMPATIBLE_N=1
MODALIAS=of:Ni2cT(null)Cqcom,i2c-qup-v2.2.1
```

**Comment by alikates** [comment]
LGTM, i guess. Also @M0Rf30 you can re-add the dma channels for SPI.

**Comment by M0Rf30** [comment]
> LGTM, i guess. Also @M0Rf30 you can re-add the dma channels for SPI.
Done
https://github.com/msm8953-mainline/linux/pull/123

**Comment by alikates** [comment]
Merging and cherry-picking into v6.4.7

**Pull request merged**
